apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    name: goappdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gopod
  template: 
    metadata:
      labels:
        app: gopod
    spec:
      imagePullSecrets:
        - name: mysecret
      containers:
      - name: gopod
        image: mrlvs/go:v1.0.0
        imagePullPolicy: Always
        env:
          - name: HOST
            value: 0.0.0.0
          - name: PORT
            value: "3000"
          - name: ROUTE_PATH
            value: /lukin
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - containerPort: 3000           