apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2021-04-14T08:59:40Z"
  name: devopsschool.k8s.local
spec:
  nodeTerminationHandler:
    enabled: true
  clusterAutoscaler:
    enabled: true
  kubeDNS:
    provider: CoreDNS
    nodeLocalDNS:
      enabled: true
  metricsServer:
    enabled: true
    insecure: true
  kubeAPIServer:
    eventTTL: 24h0m0s
    featureGates:
      EphemeralContainers: "true"
      GracefulNodeShutdown: "true"
      HPAContainerMetrics: "true"
      HPAScaleToZero: "true"
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://devopsschool-kops-state/devopsschool.k8s.local
  containerRuntime: containerd
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    featureGates:
      EphemeralContainers: "true"
      GracefulNodeShutdown: "true"
      HPAContainerMetrics: "true"
      HPAScaleToZero: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.20.6
  masterPublicName: api.devopsschool.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-04-14T08:59:40Z"
  labels:
    kops.k8s.io/cluster: devopsschool.k8s.local
  name: master-eu-central-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210315
  machineType: t3a.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  rootVolumeSize: 20
  subnets:
  - eu-central-1a

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-04-14T08:59:41Z"
  labels:
    kops.k8s.io/cluster: devopsschool.k8s.local
  name: nodes-eu-central-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210315
  machineType: t3a.small
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-central-1a
  role: Node
  rootVolumeSize: 20
  subnets:
  - eu-central-1a
