apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
      - name: myalpine
        image: alpine
        command: ["date"]
      restartPolicy: Never
