# ABAC -> RBAC

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myrole
rules:
  - apiGroups: ["apps"]
    # kubectl api-resources
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list"]
  - apiGroups: [""] # for core API Group where apiVersion field has only API Version without explicit reference to API Group
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myclusterrole
rules:
  - apiGroups: ["apps"]
    # kubectl api-resources
    resources: ["deployments"]
    resourceNames: ["ali"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""] # for core API Group where apiVersion field has only API Version without explicit reference to API Group
    # kubectl api-resources
    resources: ["pods", "namespaces"]
    verbs: ["get", "list"]


# For PSP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mypsprole
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
