apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-lukin.fullname" . }}
  labels:
    {{- include "chart-lukin.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "chart-lukin.selectorLabels" . | nindent 4 }}
