image:
  repository: nginx
  tag: 1.18-alpine

imagePullSecrets:
  - name: artifactory

ingress:
  hosts:
    - host: example-dev.com
      paths:
      - path: /asdad
        backend:
          serviceName: chart-new.local
          servicePort: 80
